spring:
  application:
    name: Utile
  datasource:
    url: jdbc:mysql://localhost:3306/utile
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 283489240636-jq61geccnle78es1rlgc0uiva9dfktks.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

springdoc:
  swagger-ui:
    show-extensions: true
    show-common-extensions: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

jwt:
  base64-secret: secret
  token-validity: 3600