INSERT INTO users (
                   username,
                   first_name,
                   last_name,
                   email,
                   password,
                   birthday,
                   mobile_phone,
                   address,
                   account_type,
                   status,
                   created_date,
                   last_modified_date,
                   created_by,
                   last_modified_by)
VALUES ('john_doe',
        'John',
        'Doe',
        'john.doe@example.com',
        '$2a$10$fAb5yDYznme2vPNov0KY1eyJfNFo4yteoeC/V1oRhJNgwwvzn52B6',
        '1990-01-01',
        '+1234567890',
        '123 Main St, Anytown, USA',
        'USER',
        'ACTIVE',
        '2024-07-26 12:00:00',
        '2024-07-26 12:00:00',
        'system',
        'system');